### ISSUE TITLE
Migrating collect to go

### ISSUE THREAD

**Issue by atakanyenel** [manoloesparta/pi#1]
Hey,
cool project !! I saw it on Reddit. I was wondering if you want to write collect.py in Golang. It uses threads, and well that's golang's deal :) It will also remove python as a dependency. So an idea would be for the server binary to check , if the data folder exists, if it does just serve the api, and if data does not exists, download it before serving it. 

I can also write it myself and create a PR, but want to learn your opinion first.

**Comment by manoloesparta** [comment]
Hey, Im really happy you want to contribute but the file you are trying to modify its a one time run only so theres not much point on modifying that. But im thinking maybe next year making a piandme v2, if you are interested I can contact you when I start the project.
